version: "3.7"
services:
  webserver:
    image: nginx:1.19-alpine
    container_name: shopify-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
      - "3456:3456"

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: shopify-php-fpm
    volumes:
      - .:/var/www/html
    ports:
      - "35729:9000"
